//Generated by gopages from src/hello.ghtml, do not edit
//This file will be overwritten during build

package pages

import(
"time"
	"io"
	"http"
	"fmt"
)
func Render(conn *http.Conn, request *http.Request){
					print := func(toPrint ...interface{}){
						io.WriteString(conn, fmt.Sprint(toPrint))
					}
					formValue := func(keyToGet string) string{
						return request.FormValue(keyToGet)
					}
					print(""); formValue("")// prevent initialization runtime error

			io.WriteString(conn, `
<html>
	<head><title>`)
 print("Hello with gopages") 
io.WriteString(conn, `</title>
	<body>
		<a href="echo">Echo example</a><br>
		<img src="gopages.png" />
		`)
 
			for i := 1 ; i < 5; i++{
		
io.WriteString(conn, `
			<h`)
 print(fmt.Sprintf("%d", i)) 
io.WriteString(conn, `>Hello gopages</h`)
 print(fmt.Sprintf("%d", i)) 
io.WriteString(conn, `>
		`)

			}
		
io.WriteString(conn, `
		<hr>
		`)

			print("page generated on " +time.LocalTime().String())
		
io.WriteString(conn, `
	</body>
</html>
`)


}
