//Generated by gopages, do not edit
//This file will be overwritten during build

package pages

import (
	"code.google.com/p/gopages/pkg"
)

func init() {
	gopages.ParsedPages["src/echo.ghtml"] = Rendersrcechoghtml
	gopages.ParsedPages["src/hello.ghtml"] = Rendersrchelloghtml
}
