//Generated by gopages from src/echo.ghtml, do not edit
//This file will be overwritten during build

package pages

import (
	"fmt"
	"net/http"
	"time"
)

func Rendersrcechoghtml(writer http.ResponseWriter, request *http.Request) {
	request.ParseForm()
	writer.Header().Set("Content-Type", "text/html")
	print := func(toPrint ...interface{}) {
		fmt.Fprint(writer, toPrint...)
	}
	formValue := func(keyToGet string) string {
		return request.FormValue(keyToGet)
	}
	print("")
	formValue("") // prevent initialization runtime error

	fmt.Fprint(writer, `
<html>
	<head><title>`)
	print("Echo with gopages")
	fmt.Fprint(writer, `</title>
	<body>
		<a href="hello" >Hello example</a> <br>
		<img src="gopages.png" />		
		<h1>Echo with gopages</h1>
		`)

	a := formValue("input")
	if len(a) > 0 {
		print("you input '" + a + "'")
	}

	fmt.Fprint(writer, `
		<form action="/echo" method="post">
			Input <input type="text" name="input"/>
			<input type="submit" value="Echo with POST"/>
		</form>
		<form action="/echo" method="get">
			Input <input type="text" name="input"/>
			<input type="submit" value="Echo with GET"/>
		</form>
			<hr>
		`)

	print("page generated on " + time.Now().String())

	fmt.Fprint(writer, `
	</body>
</html>
`)

}
