//Generated by gopages from src/hello.ghtml, do not edit
//This file will be overwritten during build

package pages

import (
	"fmt"
	"net/http"
	"time"
)

func Rendersrchelloghtml(conn http.ResponseWriter, request *http.Request) {
	conn.Header().Set("Content-Type", "text/html")
	print := func(toPrint ...interface{}) {
		fmt.Fprint(conn, toPrint...)
	}
	formValue := func(keyToGet string) string {
		return request.FormValue(keyToGet)
	}
	print("")
	formValue("") // prevent initialization runtime error

	fmt.Fprint(conn, `
<html>
	<head><title>`)
	print("Hello with gopages")
	fmt.Fprint(conn, `</title>
	<body>
		<a href="echo">Echo example</a><br>
		<img src="gopages.png" />
		`)

	for i := 1; i < 5; i++ {

		fmt.Fprint(conn, `
			<h`)
		print(i)
		fmt.Fprint(conn, `>Hello gopages</h`)
		print(i)
		fmt.Fprint(conn, `>
		`)

	}

	fmt.Fprint(conn, `
		<hr>
		`)

	print("page generated on " + time.Now().String())

	fmt.Fprint(conn, `
	</body>
</html>
`)

}
